import { InjectQueue } from '@nestjs/bullmq';
import { Injectable } from '@nestjs/common';
import { type JobsOptions, Queue } from 'bullmq';

import { AuthEmailJobName, type AuthEmailPayload } from './auth-email.types';
import { AUTH_EMAIL_QUEUE } from './queue.constants';

@Injectable()
export class AuthEmailProducer {
  /** Useful in tests that need last raw tokens generated by API flow */
  public lastVerificationToken: string | null = null;
  public lastResetToken: string | null = null;

  constructor(
    @InjectQueue(AUTH_EMAIL_QUEUE)
    private readonly queue: Queue<AuthEmailPayload>,
  ) {}

  async enqueueVerificationEmail(to: string, token: string): Promise<void> {
    this.lastVerificationToken = token;
    await this.queue.add(AuthEmailJobName.SendVerificationEmail, { to, token }, this.jobOptions());
  }

  async enqueuePasswordResetEmail(to: string, token: string): Promise<void> {
    this.lastResetToken = token;
    await this.queue.add(AuthEmailJobName.SendPasswordResetEmail, { to, token }, this.jobOptions());
  }

  private jobOptions(): JobsOptions {
    return {
      attempts: 3,
      backoff: {
        type: 'exponential' as const,
        delay: 1000,
      },
      removeOnComplete: true,
      removeOnFail: 50,
    };
  }
}
